// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAczrCUsYW0j5saKDBm-8AnJVYoDA4cvDk',
    appId: '1:593298981209:web:e2816efa418f9359a08c48',
    messagingSenderId: '593298981209',
    projectId: 'placement-preparation-ap-bdd01',
    authDomain: 'placement-preparation-ap-bdd01.firebaseapp.com',
    storageBucket: 'placement-preparation-ap-bdd01.firebasestorage.app',
    measurementId: 'G-6YMV04RPXL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkxcXf73TG8CZC2ffMHgmtEjiIf4wj3Yc',
    appId: '1:593298981209:ios:fc65cea646cc193ea08c48',
    messagingSenderId: '593298981209',
    projectId: 'placement-preparation-ap-bdd01',
    storageBucket: 'placement-preparation-ap-bdd01.firebasestorage.app',
    iosBundleId: 'com.example.placementPreparationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkxcXf73TG8CZC2ffMHgmtEjiIf4wj3Yc',
    appId: '1:593298981209:ios:fc65cea646cc193ea08c48',
    messagingSenderId: '593298981209',
    projectId: 'placement-preparation-ap-bdd01',
    storageBucket: 'placement-preparation-ap-bdd01.firebasestorage.app',
    iosBundleId: 'com.example.placementPreparationApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAczrCUsYW0j5saKDBm-8AnJVYoDA4cvDk',
    appId: '1:593298981209:web:66e384df554875f8a08c48',
    messagingSenderId: '593298981209',
    projectId: 'placement-preparation-ap-bdd01',
    authDomain: 'placement-preparation-ap-bdd01.firebaseapp.com',
    storageBucket: 'placement-preparation-ap-bdd01.firebasestorage.app',
    measurementId: 'G-X5CJ68VZCK',
  );
}
